version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - "> 3.1.0"
  - dependency-name: husky
    versions:
    - ">= 4.a, < 5"
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
    - 14.14.27
